
@baseurl = http://localhost:3333

# Health Check
# @name healthCheck
GET {{baseurl}}/health-check

###

# Get Rooms
# @name getRooms
GET {{baseurl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseurl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "SALA DE TESTE DEFINITIVO",
  "description": "Esta é uma sala de teste para teste."
}

###

@roomId =  {{createRoom.response.body.$.roomId}}
###

# Get Room Questions
# @name getRoomQuestions
GET {{baseurl}}/rooms/{{roomId}}/questions

### 

# Create Question
# @name createQuestion
POST {{baseurl}}/rooms/{{roomId}}/question
Accept: application/json
Content-Type: application/json

{
  "question": "Qual é o objetivo desta sala?"
}